module.exports =
    NOTIFICATOR_TRANSPORT_XMPP: 'xmpp'
    NOTIFICATOR_TRANSPORT_SMTP: 'smtp'
    NOTIFICATOR_TRANSPORT_SWITCHING: 'switching'
    NOTIFICATOR_TRANSPORT_MANDRILL_SMTP: 'mandrill-smtp'
    NOTIFICATOR_TRANSPORT_FACEBOOK_XMPP: 'facebook-xmpp'